# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e3c36eceb68635271fb3f43cab5c2674dbbe720a3a6fff43df8707db2377b6d2d8aec264931c8264151207c32fdffb3f0a729c93bfce2ec1fadaa7afae339a

test:
  secret_key_base: c2f9b1e17e8625fc4e324677851398c0819349bfdae1e230db24238b3c887e5d2f2814d895670a1074c274fcdf818d412433b4db48910d279cb436cd931711b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
